project_id = "vyvjlhznffwstaxbpini"

[functions.chat]
verify_jwt = false

[functions.process-document]
verify_jwt = false

[functions.ingest-url]
verify_jwt = false

[functions.retrieve]
verify_jwt = false
